name: Publish Package

on:
  push:
    branches: ["release"]

jobs:
  test:
    name: Test library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
        name: Install packages
      - run: npm test
        name: Test library

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          scope: "@easygrating"
      - run: npm ci
        name: Install packages
      - run: npm publish --access=public
        name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}